## Lesson 6

--> Index_Alignment  
--> Index Alignment  
--> Universal Functions  

### Index_Alignment

In [4]:
import pandas as pd

area = pd.Series({
    'Hyderabad':38317000,
    'Uttar Pradesh':238875000,
    'Mumbai':127684000
},name='area')

population = pd.Series({
    'Uttar Pradesh':240928,
    'Hyderabad':112077,
    'Banglore':191791
},name='population')

In [5]:
population/area   # We are Getting some NaN values[Not a Number] because the values do not have an entry for it 
                    # Example - Banglore we provided value for banglore in population Series object but not in area series object

Banglore              NaN
Hyderabad        0.002925
Mumbai                NaN
Uttar Pradesh    0.001009
dtype: float64

In [8]:
area.index.intersection(population.index)  # This gives the indexes which are common in both the Series Obejcts 

Index(['Hyderabad', 'Uttar Pradesh'], dtype='object')

In [30]:
a = pd.Series([2,3,4,5,6,7], index =[0,1,2,3,4,5])
b = pd.Series([1,2,3,4], index=[1,2,3,4])
print(a,'\n')
print(b,'\n')
print(a+b)   # Here the first and last values are NaN 
            # The reason is because 
            # index 0 is present in 'a' and not in 'b'
            # index 5 is present in 'a' and not in 'b'

0    2
1    3
2    4
3    5
4    6
5    7
dtype: int64 

1    1
2    2
3    3
4    4
dtype: int64 

0     NaN
1     4.0
2     6.0
3     8.0
4    10.0
5     NaN
dtype: float64


### Index Alignment 

In [17]:
import pandas as pd
import numpy as np

A = pd.DataFrame(np.random.randint(0,11,(2,2)),columns=['a','b'])

print(A,'\n')

B = pd.DataFrame(np.random.randint(20,50,(3,3)),columns=['b','c','a'])

print(B)

   a  b
0  6  2
1  5  7 

    b   c   a
0  25  43  48
1  46  22  28
2  48  39  45


In [18]:
print(A+B)  

      a     b   c
0  54.0  27.0 NaN
1  33.0  53.0 NaN
2   NaN   NaN NaN


### Universal Functions

In [19]:
A = np.random.randint(0,12,(3,4))
print(A)

[[ 6  7  3  6]
 [ 2  8  6  7]
 [10 11  5  5]]


In [20]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-4,  1,  3,  1],
       [ 4,  4,  2, -1]])

In [21]:
df = pd.DataFrame(A,columns=list("BACD"))
df

B   A  C  D
0   6   7  3  6
1   2   8  6  7
2  10  11  5  5

In [24]:
df-df.iloc[0]

B  A  C  D
0  0  0  0  0
1 -4  1  3  1
2  4  4  2 -1

In [27]:
print(df,'\n')

print(df.subtract(df['C'],axis=0))

    B   A  C  D
0   6   7  3  6
1   2   8  6  7
2  10  11  5  5 

   B  A  C  D
0  3  4  0  3
1 -4  2  0  1
2  5  6  0  0


In [28]:
halfrow = df.iloc[0,::2]
halfrow

B    6
C    3
Name: 0, dtype: int32

In [29]:
df-halfrow

A    B    C   D
0 NaN  0.0  0.0 NaN
1 NaN -4.0  3.0 NaN
2 NaN  4.0  2.0 NaN